services:
  test-postgres-database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - PostgreSQL:/var/libs/postgres
    networks:
      - test-postgres-network

  test-pgadmin-service:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - test-postgres-database
    networks:
      - test-postgres-network

volumes:
  PostgreSQL:

networks:
  test-postgres-network:
    driver: bridge